---
- name: Combined Playbook Packages and Configuration
  hosts: all
  gather_facts: true
  tasks:
    - name: Include Packages Tasks
      include_tasks: Packages.yml

    - name: Include Konfigurasi Tasks
      include_tasks: konfigurasi.yml
    - name: Include Handler Tasks
      include_tasks: handler.yml    