---
- name: Upgrade and Reboot RHEL Linux distros
  hosts: all
  tasks:
    # Upgrade RHEL family OS packages
    - name: Upgrade RHEL Family OS packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
- name: Play to Packages
  hosts: all
  tasks:
  - name: Install php and nginx
    package:
      name:
        - php
        - nginx
      state: present
  

      
